trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    include:
      - docker/Dockerfile
      - pipelines/docker_deploy.yml

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build job
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              buildContext: $(Build.SourcesDirectory)
              command: buildAndPush
              repository: leriksen/docker-as-command
              dockerfile: $(Build.SourcesDirectory)/docker/Dockerfile
              containerRegistry: docker.io
              tags: |
                0.0.1-$(Build.BuildId)
                latest